#!/bin/sh

case $1 in
        start) modprobe ppp_async;
		adsl-start&;;
        stop) adsl-stop;
	      modprobe -r ppp_async;;
	restart) adsl-stop;
		modprobe -r ppp_async;
		modprobe ppp_async;
		adsl_start&;;
        enable) rm -f /persistent/etc/rc.d/S12pppoe;
                ln -s /persistent/etc/init.d/pppoe /persistent/etc/rc.d/S12pppoe;;
        disable) rm -f /persistent/etc/rc.d/S12pppoe;;
        *) echo 'Syntax: /etc/init.d/pppoe [command]'
           echo ''
           echo '       Available commands:'
           echo '               start   Start the service'
           echo '               stop    Stop the service'
           echo '               restart Restart the service'
           echo '               enable  Enable service autostart'
           echo '               disable Disable service autostart'
esac
