#!/bin/sh
if [ "$1" = "" ]; then
        echo "FAIL: input error" > /var/lib/asterisk/static-http/voiceresult
        exit 1
fi

if [ "$1" = "backup" ]; then
    [ -d /mnt/sd/voicemail ] && mkdir /mnt/sd/voicemail
    /bin/cp -rf /var/lib/asterisk/sounds/voicemail/* /mnt/sd/voicemail
    echo "PASS: success copy voicemail files to mmc/sd card" > /var/lib/asterisk/static-http/voiceresult
else
        if [ "$1" = "delete" ]; then
            for filename in `find /var/lib/asterisk/sounds/voicemail/ -name *.txt`; do
                rm -rf $filename
            done
            for filename in `find /var/lib/asterisk/sounds/voicemail/ -name *.alaw`; do
                rm -rf $filename
            done            
            for filename in `find /var/lib/asterisk/sounds/voicemail/ -name *.gsm`; do
                rm -rf $filename
            done            
            for filename in `find /var/lib/asterisk/sounds/voicemail/ -name *.WAV`; do
                rm -rf $filename
            done            
            for filename in `find /var/lib/asterisk/sounds/voicemail/ -name *.wav`; do
                rm -rf $filename
            done 
            echo "PASS: success delete all voicemail files" > /var/lib/asterisk/static-http/voiceresult                   
        else
            echo "FAIL: input error" > /var/lib/asterisk/static-http/voiceresult
        fi
fi