#!/bin/sh                                                                       
# Start up file for dhcpd                                                       
                                                                                
case $1 in                                                                      
        start) /usr/sbin/udhcpd > /dev/null 2>&1 &;;                                              
        stop) killall -9 udhcpd;;                                               
        restart) killall -9 udhcpd;                                             
                 /usr/sbin/udhcpd > /dev/null 2>&1 &;;                                            
        enable) rm -f /persistent/etc/rc.d/S85dhcpd;                            
                ln -s /persistent/etc/init.d/dhcpd /persistent/etc/rc.d/S85dhcpd
        disable) rm -f /persistent/etc/rc.d/S85dhcpd;;                          
        *) cat <<EOF;;                                                          
Syntax: /etc/init.d/dhcpd [command]                                             
                                                                                
Available commands:                                                             
        start   Start the service                                               
        stop    Stop the service                                                
        restart Restart the service                                             
        enable  Enable service autostart                                        
        disable Disable service autostart                                       
EOF                                                                             
esac 
